### ISSUE TITLE
[SOLVED] Bunny Prisoner Locating Fails

### ISSUE THREAD

**Issue by primalbet** [tandav/google-foobar#1]
I spent hours writing out the algorithm and applying it myself and I always have 2/5 failing test cases. I tried your solution and there are still 2/5 failing test cases.. WTF? I'm so pissed off, did google fuck up something? Is this a bug? I literally can't find what would be the test case where it fails. It just says

Test 1 passed!
Test 2 passed!
Test 3 passed!
Test 4 failed.
Test 5 failed.

EDIT: finally solved on my own. The problem is the limit. The range is from 1-100000. There was a test case that does something like 100000*100000 in which case `int` wouldn't be able to hold that massive number, so I needed to create a temp `long` variables for both `x` and `y`.

**Comment by tandav** [comment]
It turns out that you code in java. And java is static typed (unlike python which is dynamic). So you need to do some extra work to handle types. Happy coding!
